{{- $r := int $.Values.replicaCount }}
{{- range $i, $v := untilStep 0 (int ($.Values.replicaCount)) 1 }}
{{- if lt $i $r }}
{{- range $key, $value := $.Values.storage.local }}
{{- if eq (toString ($i)) $key }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: {{ template "rabbitmq.name" $ }}
    podindex: '{{ $i }}'
  name: {{ template "rabbitmq.name" $ }}-{{ $i }}
spec:
  capacity:
    storage: {{ $.Values.storage.capacity }}
  accessModes:
  - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ $value.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "kubernetes.io/hostname"
          operator: "In"
          values:
          - {{ $value.host }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
