apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.name" $ }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ template "rabbitmq.name" $ }}
spec:
  publishNotReadyAddresses: true # Create endpoints also if the related pod isn't ready
  selector:
    app: {{ template "rabbitmq.name" $ }}
  type: ClusterIP
  ports:
  - name: rabbitmq
    protocol: TCP
    port: {{ $.Values.service.rabbitmq.port }}
  - name: rabbitmqhttp
    protocol: TCP
    port: {{ $.Values.service.rabbitmqhttp.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.name" $ }}-headless
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ template "rabbitmq.name" $ }}-headless
spec:
  publishNotReadyAddresses: true # Create endpoints also if the related pod isn't ready
  selector:
    app: {{ template "rabbitmq.name" $ }}
  clusterIP: None
  ports:
  - name: rabbitmq
    protocol: TCP
    port: {{ $.Values.service.rabbitmq.port }}
  - name: rabbitmqhttp
    protocol: TCP
    port: {{ $.Values.service.rabbitmqhttp.port }}